### ISSUE TITLE
Expected code release date

### ISSUE THREAD

**Issue by nickk124** [BioMedIA-MBZUAI/XReal#1]
Hi,

I love your model and paper! I wanted to try out training conditional LDMs for my own data, but I found that the original LDM repository is old and seems difficult to get working for custom datasets. I was just wondering when you plan to release your own code, as I'd like to check it out instead.

Thanks!

**Comment by aneesurhashmi** [comment]
Hi @nickk124. We have released the code. Please feel free to check.

**Comment by nickk124** [comment]
Great, much appreciated!
